//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtimeFilterDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealtimeFilterDemo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Nokia example application demonstrating the real-time use of effects provided by the Nokia Imaging SDK. The effects are applies to the stream of images received from the camera device..
        /// </summary>
        public static string AboutPage_AboutRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_AboutRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.github.com/nokia-developer/real-time-filter-demo/.
        /// </summary>
        public static string AboutPage_Hyperlink_Project {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time Filter Demo version {0}.
        /// </summary>
        public static string AboutPage_VersionRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageButtonText {
            get {
                return ResourceManager.GetString("AboutPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL-TIME FILTER DEMO.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antique.
        /// </summary>
        public static string Filter_Antique {
            get {
                return ResourceManager.GetString("Filter_Antique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Enhance.
        /// </summary>
        public static string Filter_AutoEnhance {
            get {
                return ResourceManager.GetString("Filter_AutoEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoon.
        /// </summary>
        public static string Filter_Cartoon {
            get {
                return ResourceManager.GetString("Filter_Cartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Weighted Grayscale.
        /// </summary>
        public static string Filter_Custom {
            get {
                return ResourceManager.GetString("Filter_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        public static string Filter_Grayscale {
            get {
                return ResourceManager.GetString("Filter_Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lomo.
        /// </summary>
        public static string Filter_Lomo {
            get {
                return ResourceManager.GetString("Filter_Lomo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Pen.
        /// </summary>
        public static string Filter_MagicPen {
            get {
                return ResourceManager.GetString("Filter_MagicPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        public static string Filter_Sepia {
            get {
                return ResourceManager.GetString("Filter_Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness.
        /// </summary>
        public static string Filter_Sharpness {
            get {
                return ResourceManager.GetString("Filter_Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        public static string Filter_Stamp {
            get {
                return ResourceManager.GetString("Filter_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPS.
        /// </summary>
        public static string MainPage_FrameRateTextBlock_Format {
            get {
                return ResourceManager.GetString("MainPage_FrameRateTextBlock_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting camera....
        /// </summary>
        public static string MainPage_StatusTextBlock_StartingCamera {
            get {
                return ResourceManager.GetString("MainPage_StatusTextBlock_StartingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next effect.
        /// </summary>
        public static string NextEffectButtonText {
            get {
                return ResourceManager.GetString("NextEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous effect.
        /// </summary>
        public static string PreviousEffectButtonText {
            get {
                return ResourceManager.GetString("PreviousEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
